apiVersion: v1
kind: ConfigMap
metadata:
  name: gdsl-api-config
  namespace: gdsl-exchange
data:
  NODE_ENV: "production"
  PORT: "8000"
  SOCKET_PORT: "8001"
  FRONTEND_URL: "https://staging.eizy.trade"
  ALLOWED_CORS_ORIGINS: "https://staging.eizy.trade,https://staging-api.eizy.trade,https://staging-socket.eizy.trade"
  DEFAULT_CHAIN: "BSC"
  DEMO_MODE: "false"
