apiVersion: batch/v1
kind: Job
metadata:
  name: gdsl-db-migration
  namespace: gdsl-exchange
spec:
  backoffLimit: 2
  template:
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: migration
          image: ghcr.io/faiyyajansari1466/gdsl-exchange-api:latest
          imagePullPolicy: Always
          command: ["npx", "prisma", "migrate", "deploy", "--schema=packages/db/prisma/schema.prisma"]
          envFrom:
            - configMapRef:
                name: gdsl-api-config
            - secretRef:
                name: gdsl-api-secrets
