#!/usr/bin/env bash
# ==============================================================================
# Zero-Downtime Blue/Green Deployment Script for Godslandx Trading API
# Droplet: 157.245.100.175 (/opt/trade_bot)
# ==============================================================================
set -euo pipefail

APP_DIR="/opt/trade_bot"
NGINX_UPSTREAM_FILE="/etc/nginx/conf.d/gdsl_upstream.conf"
STATE_FILE="${APP_DIR}/.active_color"

cd "${APP_DIR}"

echo "===================================================================="
echo "🚀 [$(date '+%Y-%m-%d %H:%M:%S')] Starting Zero-Downtime Deployment..."
echo "===================================================================="

# 1. Pull latest code
echo "📥 Pulling latest Git changes..."
git pull origin main

# 2. Run Database Migrations (non-breaking, backward compatible)
echo "🗄️ Running Prisma database migrations..."
if [ -f "package.json" ]; then
    npm run db:migrate --if-present || echo "⚠️ Migration step finished or skipped."
fi

# 3. Determine active and idle colors
if [ ! -f "${STATE_FILE}" ]; then
    echo "blue" > "${STATE_FILE}"
fi

CURRENT_COLOR=$(cat "${STATE_FILE}")

if [ "${CURRENT_COLOR}" = "blue" ]; then
    TARGET_COLOR="green"
    TARGET_API_PORT="8002"
    TARGET_SOCKET_PORT="8003"
    OLD_API_PORT="8000"
    OLD_SOCKET_PORT="8001"
else
    TARGET_COLOR="blue"
    TARGET_API_PORT="8000"
    TARGET_SOCKET_PORT="8001"
    OLD_API_PORT="8002"
    OLD_SOCKET_PORT="8003"
fi

echo "🟢 Active Color : ${CURRENT_COLOR} (API Port ${OLD_API_PORT})"
echo "🟡 Target Color : ${TARGET_COLOR} (API Port ${TARGET_API_PORT})"

# 4. Build and start target container
echo "🔨 Building Docker image and starting ${TARGET_COLOR} instance..."

API_HOST_PORT="${TARGET_API_PORT}" \
SOCKET_HOST_PORT="${TARGET_SOCKET_PORT}" \
docker compose -p "gdsl_${TARGET_COLOR}" up -d --build api socket

# 5. Health Check Verification on Target Container
HEALTH_URL="http://127.0.0.1:${TARGET_API_PORT}/health"
echo "🩺 Verifying health on ${HEALTH_URL}..."

MAX_RETRIES=20
RETRY_COUNT=0
HEALTHY=false

while [ ${RETRY_COUNT} -lt ${MAX_RETRIES} ]; do
    HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" "${HEALTH_URL}" || true)
    if [ "${HTTP_CODE}" = "200" ]; then
        echo "✅ Healthcheck PASSED on ${TARGET_COLOR} (HTTP 200 OK)"
        HEALTHY=true
        break
    fi
    echo "⏳ Waiting for ${TARGET_COLOR} container to warm up... (Attempt $((RETRY_COUNT+1))/${MAX_RETRIES}, Code: ${HTTP_CODE})"
    sleep 2
    RETRY_COUNT=$((RETRY_COUNT + 1))
done

if [ "${HEALTHY}" = false ]; then
    echo "❌ Healthcheck FAILED on target ${TARGET_COLOR}! Rolling back..."
    echo "🛑 Stopping failed ${TARGET_COLOR} instance..."
    docker compose -p "gdsl_${TARGET_COLOR}" stop api socket || true
    echo "🛡️ Current ${CURRENT_COLOR} instance was NOT touched. Zero downtime maintained."
    exit 1
fi

# 6. Atomic Nginx Switch & Reload
echo "🔄 Switching Nginx upstream to ${TARGET_COLOR}..."

cat <<EOF | tee "${NGINX_UPSTREAM_FILE}" > /dev/null
# Generated by deploy-zero-downtime.sh on $(date)
upstream api_cluster {
    server 127.0.0.1:${TARGET_API_PORT} max_fails=2 fail_timeout=5s;
    server 127.0.0.1:${OLD_API_PORT} backup;
    keepalive 32;
}

upstream socket_cluster {
    ip_hash;
    server 127.0.0.1:${TARGET_SOCKET_PORT} max_fails=2 fail_timeout=5s;
    server 127.0.0.1:${OLD_SOCKET_PORT} backup;
}
EOF

# Test Nginx syntax before reload
nginx -t
# Reload Nginx without dropping a single packet (graceful worker handover)
nginx -s reload

echo "✨ Nginx reloaded successfully! New traffic is now routed to ${TARGET_COLOR}."

# 7. Drain in-flight connections on old container
DRAIN_SECONDS=15
echo "⏳ Draining existing in-flight connections on ${CURRENT_COLOR} (${DRAIN_SECONDS}s)..."
sleep ${DRAIN_SECONDS}

# 8. Stop old container
echo "🛑 Gracefully shutting down old ${CURRENT_COLOR} instance..."
docker compose -p "gdsl_${CURRENT_COLOR}" stop api socket || true

# 9. Update state file
echo "${TARGET_COLOR}" > "${STATE_FILE}"

# 10. Also ensure singleton services (trading-engine & worker) are updated cleanly
echo "🤖 Updating background trading engine and workers..."
docker compose up -d --no-deps trading-engine worker

echo "===================================================================="
echo "🎉 Zero-Downtime Deployment COMPLETED SUCCESSFULLY! (${TARGET_COLOR} active)"
echo "===================================================================="
